# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: L LAB
# Description of the Site
description: Mr.Liu's Tech Blog
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Programming, Blog, Computer Science
# URL for the Image of custom Favicon
favicon-url: https://img1.imgtp.com/2023/07/19/8LmSe0Gv.png


# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://pic1.zhimg.com/80/v2-28843bff930b36498904ec33c2e21232_1440w.webp?source=1940ef5c

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lingaoliu105@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: Liu Lingao
github_username:  lingaoliu105
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: KleeSina

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Lingao

# Name of the Author
author-name: Liu Lingao
# URL for the Image of the Author
author-image: https://img1.imgtp.com/2023/07/19/IjZZfUM9.jpg
# 60 Words About the Author
author-about: I don't major in repairing computers, but I'd like to help.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/lingaoliu105

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
